### ISSUE TITLE
TBN EPIC-Kitchens-100 features from JPoSE's repo.

### ISSUE THREAD

**Issue by haoshuai714** [aranciokov/ranp#1]
The EPIC-Kichens-100 feature  download link is broken. Could you give me a new link? Thanks!

**Comment by haoshuai714** [comment]
Could you please provide the download link of EPIC dataset? Thanks!

**Comment by aranciokov** [comment]
> The EPIC-Kichens-100 feature download link is broken. Could you give me a new link? Thanks!

Hi, thanks for letting me know. I've fixed it now. The features can be found here: https://drive.google.com/file/d/16_WXNg2aziVBsWjc1_egE4YjnJ_aKbrM/view?usp=sharing
