### ISSUE TITLE
EPIC_100_retrieval_test_sentence.csv

### ISSUE THREAD

**Issue by haoshuai714** [aranciokov/ranp#2]
when test phase, I have a bug: 
FileNotFoundError: [Errno 2] No such file or directory: 'annotation/epic100RET/EPIC_100_retrieval_test_sentence.csv'

could you give me a link about "EPIC_100_retrieval_test_sentence.csv"?

**Comment by haoshuai714** [comment]
Could you give me a link about "EPIC_100_retrieval_test_sentence.csv"? Thank you!

**Comment by aranciokov** [comment]
Hi, thanks for letting me know. You can find this file [here](https://raw.githubusercontent.com/epic-kitchens/epic-kitchens-100-annotations/master/retrieval_annotations/EPIC_100_retrieval_test_sentence.csv).

Thanks

**Comment by haoshuai714** [comment]
Thanks!

**Comment by haoshuai714** [comment]
Does your code include relevant code for the EPIC-KITCHENS-100 Multi-Instance Retrieval Challenge submission format?

**Comment by aranciokov** [comment]
Hi, no it does not.
