### ISSUE TITLE
No 'msrvtt_train.json' file

### ISSUE THREAD

**Issue by YasmineXXX** [aranciokov/ranp#3]
I couldn't find the 'msrvtt_train.json' file, which should be in 'annotation/msr-vttRET'.

**Comment by aranciokov** [comment]
Hi @YasmineXXX, thanks for letting me know. You can find the file here: [google drive link](https://drive.google.com/file/d/1TYPHLVocDgbQbmLEg3d2rv_FkDqiyeOe/view?usp=drive_link)

Let me know if you encounter any other issue.
Alex

**Comment by YasmineXXX** [comment]
Hi @aranciokov , thanks
